### ISSUE TITLE
Using tensorframes on Databricks (Community Edition)

### ISSUE THREAD

**Issue by ts270890** [tjhunter/tensorframes#30]
Hi I have installed the Maven Artifact of tensorframes on Databricks. It was successfuly added and was attached to the cluster. However, when I tried to `import tensorflow` in the code, I got an import error that no module named tensorflow exist.  I would like to know if you have any idea to work around this. Thanks.

**Comment by tjhunter** [comment]
The `tensorframes` artifact embeds a copy of the c++ part of tensorflow, not the python wrapper. You will need to install them separately.

Right now, the Databricks environment does not handle python wheel packages, so you will have to install the python package separately. Run this command in a notebook (you only need to do it once on a cluster). After running this command, you may need to attach and detach the notebook if you get an error message about protocol buffers.

```
sudo /databricks/python/bin/pip install  https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl
```

I am going to close the ticket for now, but reopen it if you run into more issues.

**Comment by ts270890** [comment]
Thank you. Its working now.
